"""auth jwt token create

Revision ID: ec45bbbd08c6
Revises: 8d2c1fcb91f9
Create Date: 2026-01-28 19:49:45.260532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec45bbbd08c6'
down_revision: Union[str, Sequence[str], None] = '8d2c1fcb91f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
